models:
  # EgoGPT 
  - model_name: egogpt_av
    script: scripts/egogpt_av_inference.py
    ckpt_path: "path/to/egogpt_av_checkpoint"
    qa_path: "path/to/question_answer_annotation.json"
    answer_dir: "output"

  # MiniCPM 
  - model_name: minicpm_av
    script: scripts/minicpm_av_infer.py
    ckpt_path: "ckpt/MiniCPM-o-2_6"
    qa_path: ""
    answer_dir: ""

  # Qwen2.5-Omni
  - model_name: qwen25_omni
    script: scripts/qwen25_av_infer.py
    ckpt_path: ""
    qa_path: ""
    answer_dir: ""

  # VideoLLaMA2
  - model_name: videollama2_av
    script: scripts/videollama2_eval.py
    ckpt_path: ""
    qa_path: ""
    answer_dir: ""
    # a / v / av
    modal_type: "a"

  # Qwen3-Omni Thinking 
  - model_name: qwen3_omni_thinking
    script: scripts/omni_infer_thinking.py
    ckpt_path: ""
    qa_path: ""
    answer_dir: ""

